
--- MIGRATE SALE CONTRACT
INSERT INTO [ERPv2].[dbo].[SalesContract]
           ([ID]
           ,[Number]
           ,[CustomerID]
           ,[FileName]
           ,[CreatedAt]
		   ,[CreatedBy])
     SELECT
	   [SALESCONTRACT].[ID]
      ,[SALESCONTRACT].[ImportNo]
      ,[SALESCONTRACT].[CustID]
	  ,[SALESCONTRACT].[FileName]
      ,[SALESCONTRACT].[ContractDate]
      ,[SALESCONTRACT].[UserBlock]
	 FROM	[LSERP].[dbo].ProdContract [SALESCONTRACT] (NOLOCK)

--- MIGRATE SALE CONTRACT DETAIL
INSERT INTO [dbo].[SalesContractDetail]
           ([SalesContractID]
           ,[LSStyle]
           ,[PurchaseOrderNumber]
           ,[CustomerPO]
           ,[CustomerStyle]
           ,[GarmentColorCode]
           ,[GarmentColorName]
           ,[Quantity]
           ,[UltimateCode]
           ,[ProductTop]
           ,[ProductBottom]
           ,[Year]
           ,[Brand]
           ,[Season]
           ,[Division]
           ,[UnitID]
           ,[Factory]
           ,[CountryName]
           ,[Destination]
           ,[UCustomterCode]
           ,[ContractNo]
           ,[MRQDate]
           ,[OrderPlacedDate]
           ,[FactoryDate]
           ,[ReqShipMonth]
           ,[Emboss]
           ,[Transfer]
           ,[Screen]
           ,[Bonding]
           ,[Pad]
           ,[Lazer]
           ,[GmtLeadTime]
           ,[MfrLeadTime]
           ,[LongestMaterialLeadTime]
           ,[TransitLeadTime]
           ,[ShippingMark]
           ,[Remark]
           ,[Updates]
           ,[CreatedBy]
           ,[LastUpdatedBy]
           ,[CreatedAt]
           ,[LastUpdatedAt]
           ,[OrderReadyDate])
     SELECT 
	   [SC].[ID]
      ,TRIM([CTDetail].[LSStyle])
      ,[CTDetail].[PONo]
      ,[CTDetail].[CustPO]
      ,[CTDetail].[StyleNo]
      ,[CTDetail].[Color]
      ,[CTDetail].[ColorExt]
      ,[CTDetail].[Qty]
      ,[CTDetail].[Ultimate_Code]
      ,[CTDetail].[Product_Top]
      ,[CTDetail].[Product_Bottom]
      ,[CTDetail].[Year]
      ,[CTDetail].[Brand]
      ,TRIM([CTDetail].[Season])
      ,[CTDetail].[Division]
      ,[CTDetail].[Unit]
      ,[CTDetail].[FTY]
      ,[CTDetail].[CountryName]
      ,[CTDetail].[Destination]
      ,[CTDetail].[CustCode]
      ,[CTDetail].[ContractNo]
      ,[CTDetail].[MRQDate]
      ,[CTDetail].[PlacedDate]
      ,[CTDetail].[FactoryDate]
      ,[CTDetail].[Req_ShipMth]
      ,[CTDetail].[Emboss]
      ,[CTDetail].[Transfer]
      ,[CTDetail].[Screen]
      ,[CTDetail].[Bonding]
      ,[CTDetail].[Pad]
      ,[CTDetail].[Lazer]
      ,[CTDetail].[GmtLT]
      ,[CTDetail].[MfrLT]
      ,[CTDetail].[MatlLT]
      ,[CTDetail].[TransitLT]
      ,[CTDetail].[ShippingMark]
      ,[CTDetail].[Remarks]
      ,[CTDetail].[Updates]
      ,[SC].[CreatedBy]
      ,[SC].[LastUpdatedBy]
      ,[SC].[CreatedAt]
      ,[SC].[LastUpdatedAt]
      ,[CTDetail].[OrderReadyDate]
  FROM 
	[LSERP].[dbo].[ProdContractLine] [CTDetail]
	LEFT JOIN [SalesContract] [SC] ON [SC].[Number] = [CTDetail].[ImportNo]
  WHERE 
	[CTDetail].[ImportNo] <> 'CTR07/19-043'
GO


