USE [ERPv2]
GO

/****** Object:  View [dbo].[ViewStorageDetailReport]    Script Date: 12/12/2022 3:06:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		NGUYEN PHUC DAT
-- Create date: 11-24-2022
-- Description:	View get item storage detail report
-- =============================================
CREATE OR ALTER VIEW  [dbo].[ViewStorageDetailReport]
AS
    SELECT DISTINCT
			 [SUB].[ID]
			,[SUB].[CustomerID]
			,[SUB].[StorageCode]
			,[SUB].[ItemID]
			,[SUB].[ItemName]
			,[SUB].[ItemColorCode]
			,[SUB].[ItemColorName]
			,[SUB].[Position]
			,[SUB].[Specify]			
			,[SUB].[GarmentColorCode]
			,[SUB].[GarmentColorName]
			,[SUB].[CustomerStyle]
			,[SUB].[Season]
			,[SUB].[UnitID]
			,[SUB].[OnHandQuantity]
			,[SUB].[ReseveredQuantity]
			,[SUB].[CanReUseQuantity]
			,[SUB].[StorageBinCode]
			,[SUB].[LotNumber]
			,[SUB].[InvoiceNumber]
			,[SUB].[PurchaseOrderNumber]
			,[SUB].[Note]
			,[SUB].[ItemCode]
			,[SUB].[Roll]
			,[SUB].[LSStyle]
			,[SUB].[DocumentNumber]
			,[SUB].[Remark]
			,[SUB].[FabricPurchaseOrderNumber]
			,[SUB].[DyeLotNumber]
			,[SUB].[InvoiceNumberNoTotal]
			,[SUB].[ItemMasterID]
			,[SUB].[IssuedQuantity]
			,[SUB].[NotReceivedQuantity]
			,[SUB].[OrderQuantity]
			,[SUB].[FabricContent]
			,[SUB].[UserFollow]
			,[SUB].[Zone]
			,[SUB].[StorageStatusID]
			,[SUB].[ProductionMethodCode]
			,[SUB].[TransactionDate]
			,[SUB].[RollNo]
			,[SUB].[OutputQuantity]
			,[SUB].[InputQuantity]
			,[SUB].[RollOutput]
			,[SUB].[Supplier]
	FROM
	(
		----- JOIN TRANSACTION WITH RECEIPTGROUPLINE, ISSUEDGROUPLINE ID IS NULL
		SELECT 
			[STORAGE].[ID]
			,[STORAGE].[CustomerID]
			,[STORAGE].[StorageCode]
			,[STORAGE].[ItemID]
			,[STORAGE].[ItemName]
			,[STORAGE].[ItemColorCode]
			,[STORAGE].[ItemColorName]
			,[STORAGE].[Position]
			,[STORAGE].[Specify]			
			,[STORAGE].[GarmentColorCode]
			,[STORAGE].[GarmentColorName]
			,[STORAGE].[CustomerStyle]
			,[STORAGE].[Season]
			,[STORAGE].[UnitID]
			,[STORAGE].[OnHandQuantity]
			,[STORAGE].[ReseveredQuantity]
			,[STORAGE].[CanReUseQuantity]
			,[STORAGE].[StorageBinCode]
			,[STORAGE].[LotNumber]
			,[STORAGE].[InvoiceNumber]
			,[STORAGE].[PurchaseOrderNumber]
			,[STORAGE].[Note]
			,[STORAGE].[ItemCode]
			,[STORAGE].[Roll]
			,[STORAGE].[LSStyle]
			,[STORAGE].[DocumentNumber]
			,[STORAGE].[Remark]
			,[STORAGE].[FabricPurchaseOrderNumber]
			,[STORAGE].[DyeLotNumber]
			,[STORAGE].[InvoiceNumberNoTotal]
			,[STORAGE].[ItemMasterID]
			,[STORAGE].[IssuedQuantity]
			,[STORAGE].[NotReceivedQuantity]
			,[STORAGE].[OrderQuantity]
			,[STORAGE].[FabricContent]
			,[STORAGE].[UserFollow]
			,[STORAGE].[Zone]
			,[STORAGE].[StorageStatusID]
			,[STORAGE].[ProductionMethodCode]
			,[TRANSACTION].[TransactionDate]
			,[TRANSACTION].[Supplier]
			,[TRANSACTION].[Roll] as RollNo
			,[TRANSACTION].[Quantity] as InputQuantity
			,OutputQuantity = (SELECT Abs(SUM(Quantity)) FROM [MaterialTransaction] SUBMS
							   WHERE [SUBMS].[StorageDetailID] = [STORAGE].[ID] AND IssuedNumber is not null AND SUBMS.ReceiptNumber is null)
	        ,RollOutput = (SELECT Abs(SUM(Roll)) FROM [MaterialTransaction] SUBMS
							   WHERE [SUBMS].[StorageDetailID] = [STORAGE].[ID] AND IssuedNumber is not null AND SUBMS.ReceiptNumber is null)
			--, COUNT([STORAGE].[ID]) AS NUMBER
		FROM
			[StorageDetail] [STORAGE] (NOLOCK)
			CROSS APPLY
			(
				SELECT TOP 1 [TransactionDate], [Roll], [Quantity], [Supplier]
				FROM [MaterialTransaction]
				WHERE [StorageDetailID] = [STORAGE].[ID] 
				AND [ReceiptGroupLineID] IS NULL AND [ReceiptNumber] IS NULL
				AND [IssuedLineID] IS NULL AND [IssuedNumber] IS NULL
			) [TRANSACTION] 	
		GROUP BY
			[STORAGE].[ID]
			,[STORAGE].[CustomerID]
			,[STORAGE].[StorageCode]
			,[STORAGE].[ItemID]
			,[STORAGE].[ItemName]
			,[STORAGE].[ItemColorCode]
			,[STORAGE].[ItemColorName]
			,[STORAGE].[Position]
			,[STORAGE].[Specify]			
			,[STORAGE].[GarmentColorCode]
			,[STORAGE].[GarmentColorName]
			,[STORAGE].[CustomerStyle]
			,[STORAGE].[Season]
			,[STORAGE].[UnitID]
			,[STORAGE].[OnHandQuantity]
			,[STORAGE].[ReseveredQuantity]
			,[STORAGE].[CanReUseQuantity]
			,[STORAGE].[StorageBinCode]
			,[STORAGE].[LotNumber]
			,[STORAGE].[InvoiceNumber]
			,[STORAGE].[PurchaseOrderNumber]
			,[STORAGE].[Note]
			,[STORAGE].[ItemCode]
			,[STORAGE].[Roll]
			,[STORAGE].[LSStyle]
			,[STORAGE].[DocumentNumber]
			,[STORAGE].[Remark]
			,[STORAGE].[FabricPurchaseOrderNumber]
			,[STORAGE].[DyeLotNumber]
			,[STORAGE].[InvoiceNumberNoTotal]
			,[STORAGE].[ItemMasterID]
			,[STORAGE].[IssuedQuantity]
			,[STORAGE].[NotReceivedQuantity]
			,[STORAGE].[OrderQuantity]
			,[STORAGE].[FabricContent]
			,[STORAGE].[UserFollow]
			,[STORAGE].[Zone]
			,[STORAGE].[StorageStatusID]
			,[STORAGE].[ProductionMethodCode]
			,[TRANSACTION].[TransactionDate]
			,[TRANSACTION].[Roll]
			,[TRANSACTION].[Quantity]
			,[TRANSACTION].[Supplier]
			-- 58408
		UNION

		---- Forecast Material
		SELECT 
			[STORAGE].[ID]
			,[STORAGE].[CustomerID]
			,[STORAGE].[StorageCode]
			,[STORAGE].[ItemID]
			,[STORAGE].[ItemName]
			,[STORAGE].[ItemColorCode]
			,[STORAGE].[ItemColorName]
			,[STORAGE].[Position]
			,[STORAGE].[Specify]			
			,[STORAGE].[GarmentColorCode]
			,[STORAGE].[GarmentColorName]
			,[STORAGE].[CustomerStyle]
			,[STORAGE].[Season]
			,[STORAGE].[UnitID]
			,[STORAGE].[OnHandQuantity]
			,[STORAGE].[ReseveredQuantity]
			,[STORAGE].[CanReUseQuantity]
			,[STORAGE].[StorageBinCode]
			,[STORAGE].[LotNumber]
			,[STORAGE].[InvoiceNumber]
			,[STORAGE].[PurchaseOrderNumber]
			,[STORAGE].[Note]
			,[STORAGE].[ItemCode]
			,[STORAGE].[Roll]
			,[STORAGE].[LSStyle]
			,[STORAGE].[DocumentNumber]
			,[STORAGE].[Remark]
			,[STORAGE].[FabricPurchaseOrderNumber]
			,[STORAGE].[DyeLotNumber]
			,[STORAGE].[InvoiceNumberNoTotal]
			,[STORAGE].[ItemMasterID]
			,[STORAGE].[IssuedQuantity]
			,[STORAGE].[NotReceivedQuantity]
			,[STORAGE].[OrderQuantity]
			,[STORAGE].[FabricContent]
			,[STORAGE].[UserFollow]
			,[STORAGE].[Zone]
			,[STORAGE].[StorageStatusID]
			,[STORAGE].[ProductionMethodCode]
			,[Receipt].[ArrivedDate]
			,[TRANSACTION].[Supplier]
			,[TRANSACTION].[Roll] as RollNo
			,[TRANSACTION].[Quantity] as InputQuantity
			,OutputQuantity = (SELECT Abs(SUM(Quantity)) FROM [MaterialTransaction] SUBMS
							   WHERE [SUBMS].[StorageDetailID] = [STORAGE].[ID] AND SUBMS.IssuedNumber is not null AND SUBMS.ReceiptNumber is null)
	        ,RollOutput = (SELECT Abs(SUM(Roll)) FROM [MaterialTransaction] SUBMS
							   WHERE [SUBMS].[StorageDetailID] = [STORAGE].[ID] AND SUBMS.IssuedNumber is not null AND SUBMS.ReceiptNumber is null)
		FROM
			[StorageDetail] [STORAGE] (NOLOCK)
			JOIN [MaterialTransaction] [TRANSACTION] (NOLOCK) ON [STORAGE].[ID] = [TRANSACTION].[StorageDetailID]
			JOIN [Receipt] [RECEIPT] (NOLOCK) ON [RECEIPT].[Number] = [TRANSACTION].[ReceiptNumber]
				AND [TRANSACTION].[ReceiptGroupLineID] IS NOT NULL
				AND [TRANSACTION].[IssuedLineID] IS NULL 
		GROUP BY
			[STORAGE].[ID]
			,[STORAGE].[CustomerID]
			,[STORAGE].[StorageCode]
			,[STORAGE].[ItemID]
			,[STORAGE].[ItemName]
			,[STORAGE].[ItemColorCode]
			,[STORAGE].[ItemColorName]
			,[STORAGE].[Position]
			,[STORAGE].[Specify]			
			,[STORAGE].[GarmentColorCode]
			,[STORAGE].[GarmentColorName]
			,[STORAGE].[CustomerStyle]
			,[STORAGE].[Season]
			,[STORAGE].[UnitID]
			,[STORAGE].[OnHandQuantity]
			,[STORAGE].[ReseveredQuantity]
			,[STORAGE].[CanReUseQuantity]
			,[STORAGE].[StorageBinCode]
			,[STORAGE].[LotNumber]
			,[STORAGE].[InvoiceNumber]
			,[STORAGE].[PurchaseOrderNumber]
			,[STORAGE].[Note]
			,[STORAGE].[ItemCode]
			,[STORAGE].[Roll]
			,[STORAGE].[LSStyle]
			,[STORAGE].[DocumentNumber]
			,[STORAGE].[Remark]
			,[STORAGE].[FabricPurchaseOrderNumber]
			,[STORAGE].[DyeLotNumber]
			,[STORAGE].[InvoiceNumberNoTotal]
			,[STORAGE].[ItemMasterID]
			,[STORAGE].[IssuedQuantity]
			,[STORAGE].[NotReceivedQuantity]
			,[STORAGE].[OrderQuantity]
			,[STORAGE].[FabricContent]
			,[STORAGE].[UserFollow]
			,[STORAGE].[Zone]
			,[STORAGE].[StorageStatusID]
			,[STORAGE].[ProductionMethodCode]
			,[Receipt].[ArrivedDate]
			,[TRANSACTION].[Supplier]
			,[TRANSACTION].[Roll]
			,[TRANSACTION].[Quantity]
	) [SUB]
GO


